<?php

namespace EdStevo\Ordering\Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder {

    public function run()
    {
        DB::table('countries')->delete();

        DB::table('countries')->insert(array(

            array("iso" => "AD", "name" => "ANDORRA", "nice_name" => "Andorra", "iso_3" => "AND", "currency_id" => "EUR", "ready" => false),
            array("iso" => "AE", "name" => "UNITED ARAB EMIRATES", "nice_name" => "United Arab Emirates", "iso_3" => "ARE", "currency_id" => "AED", "ready" => false),
            array("iso" => "AF", "name" => "AFGHANISTAN", "nice_name" => "Afghanistan", "iso_3" => "AFG", "currency_id" => "AFN", "ready" => false),
            array("iso" => "AG", "name" => "ANTIGUA AND BARBUDA", "nice_name" => "Antigua and Barbuda", "iso_3" => "ATG", "currency_id" => "XCD", "ready" => false),
            array("iso" => "AI", "name" => "ANGUILLA", "nice_name" => "Anguilla", "iso_3" => "AIA", "currency_id" => "XCD", "ready" => false),
            array("iso" => "AL", "name" => "ALBANIA", "nice_name" => "Albania", "iso_3" => "ALB", "currency_id" => "ALL", "ready" => false),
            array("iso" => "AM", "name" => "ARMENIA", "nice_name" => "Armenia", "iso_3" => "ARM", "currency_id" => "AMD", "ready" => false),
            array("iso" => "AN", "name" => "NETHERLANDS ANTILLES", "nice_name" => "Netherlands Antilles", "iso_3" => "ANT", "currency_id" => "ANG", "ready" => false),
            array("iso" => "AO", "name" => "ANGOLA", "nice_name" => "Angola", "iso_3" => "AGO", "currency_id" => "AOA", "ready" => false),
            array("iso" => "AQ", "name" => "ANTARCTICA", "nice_name" => "Antarctica", "iso_3" => "ATA","currency_id" => null, "ready" => false),
            array("iso" => "AR", "name" => "ARGENTINA", "nice_name" => "Argentina", "iso_3" => "ARG", "currency_id" => "ARS", "ready" => false),
            array("iso" => "AS", "name" => "AMERICAN SAMOA", "nice_name" => "American Samoa", "iso_3" => "ASM", "currency_id" => "GBP", "ready" => false),
            array("iso" => "AT", "name" => "AUSTRIA", "nice_name" => "Austria", "iso_3" => "AUT", "currency_id" => "EUR", "ready" => false),
            array("iso" => "AU", "name" => "AUSTRALIA", "nice_name" => "Australia", "iso_3" => "AUS", "currency_id" => "AUD", "ready" => false),
            array("iso" => "AW", "name" => "ARUBA", "nice_name" => "Aruba", "iso_3" => "ABW", "currency_id" => "AWG", "ready" => false),
            array("iso" => "AX", "name" => "ALAND ISLANDS", "nice_name" => "Aland Islands", "iso_3" => "ALA", "currency_id" => "EUR", "ready" => false),
            array("iso" => "AZ", "name" => "AZERBAIJAN", "nice_name" => "Azerbaijan", "iso_3" => "AZE", "currency_id" => "AZN", "ready" => false),
            array("iso" => "BA", "name" => "BOSNIA AND HERZEGOVINA", "nice_name" => "Bosnia and Herzegovina", "iso_3" => "BIH", "currency_id" => "BAM", "ready" => false),
            array("iso" => "BB", "name" => "BARBADOS", "nice_name" => "Barbados", "iso_3" => "BRB", "currency_id" => "FJD", "ready" => false),
            array("iso" => "BD", "name" => "BANGLADESH", "nice_name" => "Bangladesh", "iso_3" => "BGD", "currency_id" => "BDT", "ready" => false),
            array("iso" => "BE", "name" => "BELGIUM", "nice_name" => "Belgium", "iso_3" => "BEL", "currency_id" => "EUR", "ready" => false),
            array("iso" => "BF", "name" => "BURKINA FASO", "nice_name" => "Burkina Faso", "iso_3" => "BFA", "currency_id" => "XOF", "ready" => false),
            array("iso" => "BG", "name" => "BULGARIA", "nice_name" => "Bulgaria", "iso_3" => "BGR", "currency_id" => "BGN", "ready" => false),
            array("iso" => "BH", "name" => "BAHRAIN", "nice_name" => "Bahrain", "iso_3" => "BHR", "currency_id" => "BHD", "ready" => false),
            array("iso" => "BI", "name" => "BURUNDI", "nice_name" => "Burundi", "iso_3" => "BDI", "currency_id" => "BIF", "ready" => false),
            array("iso" => "BJ", "name" => "BENIN", "nice_name" => "Benin", "iso_3" => "BEN", "currency_id" => "XOF", "ready" => false),
            array("iso" => "BL", "name" => "SAINT BARTHELEMY", "nice_name" => "Saint Barthelemy", "iso_3" => "BLM", "currency_id" => "EUR", "ready" => false),
            array("iso" => "BM", "name" => "BERMUDA", "nice_name" => "Bermuda", "iso_3" => "BMU", "currency_id" => "BMD", "ready" => false),
            array("iso" => "BN", "name" => "BRUNEI", "nice_name" => "Brunei", "iso_3" => "BRN", "currency_id" => "BND", "ready" => false),
            array("iso" => "BO", "name" => "BOLIVIA", "nice_name" => "Bolivia", "iso_3" => "BOL", "currency_id" => "BOB", "ready" => false),
            array("iso" => "BQ", "name" => "BONAIRE, SINT EUSTATIUS AND SABA", "nice_name" => "Bonaire, Sint Eustatius and Saba", "iso_3" => "BES", "currency_id" => "ANG", "ready" => false),
            array("iso" => "BR", "name" => "BRAZIL", "nice_name" => "Brazil", "iso_3" => "BRA", "currency_id" => "BRL", "ready" => false),
            array("iso" => "BS", "name" => "BAHAMAS", "nice_name" => "Bahamas", "iso_3" => "BHS", "currency_id" => "BSD", "ready" => false),
            array("iso" => "BT", "name" => "BHUTAN", "nice_name" => "Bhutan", "iso_3" => "BTN", "currency_id" => "BTN", "ready" => false),
            array("iso" => "BV", "name" => "BOUVET ISLAND", "nice_name" => "Bouvet Island", "iso_3" => "BVT","currency_id" => "NOK", "ready" => false),
            array("iso" => "BW", "name" => "BOTSWANA", "nice_name" => "Botswana", "iso_3" => "BWA", "currency_id" => "GBP", "ready" => false),
            array("iso" => "BY", "name" => "BELARUS", "nice_name" => "Belarus", "iso_3" => "BLR", "currency_id" => "BYR", "ready" => false),
            array("iso" => "BZ", "name" => "BELIZE", "nice_name" => "Belize", "iso_3" => "BLZ", "currency_id" => "BZD", "ready" => false),
            array("iso" => "CA", "name" => "CANADA", "nice_name" => "Canada", "iso_3" => "CAN", "currency_id" => "CAD", "ready" => false),

        ));

        DB::table('countries')->insert(array(

            array("iso" => "CC", "name" => "COCOS (KEELING) ISLANDS", "nice_name" => "Cocos (Keeling) Islands", "iso_3" => "CCK", "currency_id" => "AUD", "ready" => false),
            array("iso" => "CD", "name" => "DEMOCRATIC REPUBLIC OF THE CONGO", "nice_name" => "Democratic Republic Of The Congo", "iso_3" => "COD", "currency_id" => "XAF", "ready" => false),
            array("iso" => "CF", "name" => "CENTRAL AFRICAN REPUBLIC", "nice_name" => "Central African Republic", "iso_3" => "CAF", "currency_id" => "XAF", "ready" => false),
            array("iso" => "CG", "name" => "CONGO", "nice_name" => "Congo", "iso_3" => "COG", "currency_id" => "XAF", "ready" => false),
            array("iso" => "CH", "name" => "SWITZERLAND", "nice_name" => "Switzerland", "iso_3" => "CHE", "currency_id" => "CHF", "ready" => false),
            array("iso" => "CI", "name" => "COTE D'IVOIRE", "nice_name" => "Cote D'Ivoire", "iso_3" => "CIV", "currency_id" => "XOF", "ready" => false),
            array("iso" => "CK", "name" => "COOK ISLANDS", "nice_name" => "Cook Islands", "iso_3" => "COK", "currency_id" => "NZD", "ready" => false),
            array("iso" => "CL", "name" => "CHILE", "nice_name" => "Chile", "iso_3" => "CHL", "currency_id" => "CLP", "ready" => false),
            array("iso" => "CM", "name" => "CAMEROON", "nice_name" => "Cameroon", "iso_3" => "CMR", "currency_id" => "XAF", "ready" => false),
            array("iso" => "CN", "name" => "CHINA", "nice_name" => "China", "iso_3" => "CHN", "currency_id" => "CNY", "ready" => false),
            array("iso" => "CO", "name" => "COLOMBIA", "nice_name" => "Colombia", "iso_3" => "COL", "currency_id" => "COP", "ready" => false),
            array("iso" => "CR", "name" => "COSTA RICA", "nice_name" => "Costa Rica", "iso_3" => "CRI", "currency_id" => "CRC", "ready" => false),
            array("iso" => "CU", "name" => "CUBA", "nice_name" => "Cuba", "iso_3" => "CUB", "currency_id" => "CUP", "ready" => false),
            array("iso" => "CV", "name" => "CAPE VERDE", "nice_name" => "Cape Verde", "iso_3" => "CPV", "currency_id" => "CVE", "ready" => false),
            array("iso" => "CW", "name" => "CURACAO", "nice_name" => "Curacao", "iso_3" => "CUW", "currency_id" => "ANG", "ready" => false),
            array("iso" => "CX", "name" => "CHRISTMAS ISLAND", "nice_name" => "Christmas Island", "iso_3" => "CXR", "currency_id" => "AUD", "ready" => false),
            array("iso" => "CY", "name" => "CYPRUS", "nice_name" => "Cyprus", "iso_3" => "CYP", "currency_id" => "EUR", "ready" => false),
            array("iso" => "CZ", "name" => "CZECH REPUBLIC", "nice_name" => "Czech Republic", "iso_3" => "CZE", "currency_id" => "CZK", "ready" => false),
            array("iso" => "DE", "name" => "GERMANY", "nice_name" => "Germany", "iso_3" => "DEU", "currency_id" => "EUR", "ready" => false),
            array("iso" => "DJ", "name" => "DJIBOUTI", "nice_name" => "Djibouti", "iso_3" => "DJI", "currency_id" => "DJF", "ready" => false),
            array("iso" => "DK", "name" => "DENMARK", "nice_name" => "Denmark", "iso_3" => "DNK", "currency_id" => "DKK", "ready" => false),
            array("iso" => "DM", "name" => "DOMINICA", "nice_name" => "Dominica", "iso_3" => "DMA", "currency_id" => "XCD", "ready" => false),
            array("iso" => "DO", "name" => "DOMINICAN REPUBLIC", "nice_name" => "Dominican Republic", "iso_3" => "DOM", "currency_id" => "DOP", "ready" => false),
            array("iso" => "DZ", "name" => "ALGERIA", "nice_name" => "Algeria", "iso_3" => "DZA", "currency_id" => "DZD", "ready" => false),
            array("iso" => "EC", "name" => "ECUADOR", "nice_name" => "Ecuador", "iso_3" => "ECU", "currency_id" => "SAR", "ready" => false),
            array("iso" => "EE", "name" => "ESTONIA", "nice_name" => "Estonia", "iso_3" => "EST", "currency_id" => "EUR", "ready" => false),
            array("iso" => "EG", "name" => "EGYPT", "nice_name" => "Egypt", "iso_3" => "EGY", "currency_id" => "EGP", "ready" => false),
            array("iso" => "EH", "name" => "WESTERN SAHARA", "nice_name" => "Western Sahara", "iso_3" => "ESH", "currency_id" => "MAD", "ready" => false),
            array("iso" => "ER", "name" => "ERITREA", "nice_name" => "Eritrea", "iso_3" => "ERI", "currency_id" => "ERN", "ready" => false),
            array("iso" => "ES", "name" => "SPAIN", "nice_name" => "Spain", "iso_3" => "ESP", "currency_id" => "EUR", "ready" => false),
            array("iso" => "ET", "name" => "ETHIOPIA", "nice_name" => "Ethiopia", "iso_3" => "ETH", "currency_id" => "ETB", "ready" => false),
            array("iso" => "FI", "name" => "FINLAND", "nice_name" => "Finland", "iso_3" => "FIN", "currency_id" => "EUR", "ready" => false),
            array("iso" => "FJ", "name" => "FIJI", "nice_name" => "Fiji", "iso_3" => "FJI", "currency_id" => "FJD", "ready" => false),
            array("iso" => "FK", "name" => "FALKLAND ISLANDS (MALVINAS)", "nice_name" => "Falkland Islands (Malvinas)", "iso_3" => "FLK", "currency_id" => "GBP", "ready" => false),
            array("iso" => "FM", "name" => "MICRONESIA", "nice_name" => "Micronesia, Federated States of", "iso_3" => "FSM", "currency_id" => "SAR", "ready" => false),
            array("iso" => "FO", "name" => "FAROE ISLANDS", "nice_name" => "Faroe Islands", "iso_3" => "FRO", "currency_id" => "DKK", "ready" => false),
            array("iso" => "FR", "name" => "FRANCE", "nice_name" => "France", "iso_3" => "FRA", "currency_id" => "EUR", "ready" => false),
            array("iso" => "GA", "name" => "GABON", "nice_name" => "Gabon", "iso_3" => "GAB", "currency_id" => "XAF", "ready" => false),
            array("iso" => "GB", "name" => "UNITED KINGDOM", "nice_name" => "United Kingdom", "iso_3" => "GBR", "currency_id" => "GBP", "ready" => true),
            array("iso" => "GD", "name" => "GRENADA", "nice_name" => "Grenada", "iso_3" => "GRD", "currency_id" => "XCD", "ready" => false),
            array("iso" => "GE", "name" => "GEORGIA", "nice_name" => "Georgia", "iso_3" => "GEO", "currency_id" => "GEL", "ready" => false),
            array("iso" => "GF", "name" => "FRENCH GUIANA", "nice_name" => "French Guiana", "iso_3" => "GUF", "currency_id" => "EUR", "ready" => false),
            array("iso" => "GG", "name" => "GUERNSEY", "nice_name" => "Guernsey", "iso_3" => "GGY", "currency_id" => "GBP", "ready" => false),
            array("iso" => "GH", "name" => "GHANA", "nice_name" => "Ghana", "iso_3" => "GHA", "currency_id" => "GHS", "ready" => false),
            array("iso" => "GI", "name" => "GIBRALTAR", "nice_name" => "Gibraltar", "iso_3" => "GIB", "currency_id" => "GBP", "ready" => false),
            array("iso" => "GL", "name" => "GREENLAND", "nice_name" => "Greenland", "iso_3" => "GRL", "currency_id" => "DKK", "ready" => false),
            array("iso" => "GM", "name" => "THE GAMBIA", "nice_name" => "The Gambia", "iso_3" => "GMB", "currency_id" => "GMD", "ready" => false),
            array("iso" => "GN", "name" => "GUINEA", "nice_name" => "Guinea", "iso_3" => "GIN", "currency_id" => "GNF", "ready" => false),
            array("iso" => "GP", "name" => "GUADELOUPE", "nice_name" => "Guadeloupe", "iso_3" => "GLP", "currency_id" => "EUR", "ready" => false),
            array("iso" => "GQ", "name" => "EQUATORIAL GUINEA", "nice_name" => "Equatorial Guinea", "iso_3" => "GNQ", "currency_id" => "XAF", "ready" => false),

        ));

        DB::table('countries')->insert(array(

            array("iso" => "GR", "name" => "GREECE", "nice_name" => "Greece", "iso_3" => "GRC", "currency_id" => "EUR", "ready" => false),
            array("iso" => "GS", "name" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "nice_name" => "South Georgia and the South Sandwich Islands", "iso_3" => "SGS","currency_id" => "GBP", "ready" => false),
            array("iso" => "GT", "name" => "GUATEMALA", "nice_name" => "Guatemala", "iso_3" => "GTM", "currency_id" => "GTQ", "ready" => false),
            array("iso" => "GU", "name" => "GUAM", "nice_name" => "Guam", "iso_3" => "GUM", "currency_id" => "SAR", "ready" => false),
            array("iso" => "GW", "name" => "GUINEA-BISSAU", "nice_name" => "Guinea-Bissau", "iso_3" => "GNB", "currency_id" => "XOF", "ready" => false),
            array("iso" => "GY", "name" => "GUYANA", "nice_name" => "Guyana", "iso_3" => "GUY", "currency_id" => "GYD", "ready" => false),
            array("iso" => "HK", "name" => "HONG KONG", "nice_name" => "Hong Kong", "iso_3" => "HKG", "currency_id" => "HKD", "ready" => false),
            array("iso" => "HM", "name" => "HEARD ISLAND AND MCDONALD ISLANDS", "nice_name" => "Heard Island and Mcdonald Islands", "iso_3" => "HMD","currency_id" => "AUD", "ready" => false),
            array("iso" => "HN", "name" => "HONDURAS", "nice_name" => "Honduras", "iso_3" => "HND", "currency_id" => "HNL", "ready" => false),
            array("iso" => "HR", "name" => "CROATIA", "nice_name" => "Croatia", "iso_3" => "HRV", "currency_id" => "HRK", "ready" => false),
            array("iso" => "HT", "name" => "HAITI", "nice_name" => "Haiti", "iso_3" => "HTI", "currency_id" => "HTG", "ready" => false),
            array("iso" => "HU", "name" => "HUNGARY", "nice_name" => "Hungary", "iso_3" => "HUN", "currency_id" => "HUF", "ready" => false),
            array("iso" => "ID", "name" => "INDONESIA", "nice_name" => "Indonesia", "iso_3" => "IDN", "currency_id" => "IDR", "ready" => false),
            array("iso" => "IE", "name" => "IRELAND", "nice_name" => "Ireland", "iso_3" => "IRL", "currency_id" => "EUR", "ready" => false),
            array("iso" => "IL", "name" => "ISRAEL", "nice_name" => "Israel", "iso_3" => "ISR", "currency_id" => "ILS", "ready" => false),
            array("iso" => "IM", "name" => "ISLE OF MAN", "nice_name" => "Isle of Man", "iso_3" => "IMN", "currency_id" => "GBP", "ready" => false),
            array("iso" => "IN", "name" => "INDIA", "nice_name" => "India", "iso_3" => "IND", "currency_id" => "INR", "ready" => false),
            array("iso" => "IO", "name" => "BRITISH INDIAN OCEAN TERRITORY", "nice_name" => "British Indian Ocean Territory", "iso_3" => "IOT", "currency_id" => "SAR", "ready" => false),
            array("iso" => "IQ", "name" => "IRAQ", "nice_name" => "Iraq", "iso_3" => "IRQ", "currency_id" => "IQD", "ready" => false),
            array("iso" => "IR", "name" => "IRAN", "nice_name" => "Iran", "iso_3" => "IRN", "currency_id" => "IRR", "ready" => false),
            array("iso" => "IS", "name" => "ICELAND", "nice_name" => "Iceland", "iso_3" => "ISL", "currency_id" => "ISK", "ready" => false),
            array("iso" => "IT", "name" => "ITALY", "nice_name" => "Italy", "iso_3" => "ITA", "currency_id" => "EUR", "ready" => false),
            array("iso" => "JE", "name" => "JERSEY", "nice_name" => "Jersey", "iso_3" => "JEY", "currency_id" => "GBP", "ready" => false),
            array("iso" => "JM", "name" => "JAMAICA", "nice_name" => "Jamaica", "iso_3" => "JAM", "currency_id" => "JMD", "ready" => false),
            array("iso" => "JO", "name" => "JORDAN", "nice_name" => "Jordan", "iso_3" => "JOR", "currency_id" => "JOD", "ready" => false),
            array("iso" => "JP", "name" => "JAPAN", "nice_name" => "Japan", "iso_3" => "JPN", "currency_id" => "JPY", "ready" => false),
            array("iso" => "KE", "name" => "KENYA", "nice_name" => "Kenya", "iso_3" => "KEN", "currency_id" => "KES", "ready" => false),
            array("iso" => "KG", "name" => "KYRGYZSTAN", "nice_name" => "Kyrgyzstan", "iso_3" => "KGZ", "currency_id" => "KGS", "ready" => false),
            array("iso" => "KH", "name" => "CAMBODIA", "nice_name" => "Cambodia", "iso_3" => "KHM", "currency_id" => "KHR", "ready" => false),
            array("iso" => "KI", "name" => "KIRIBATI", "nice_name" => "Kiribati", "iso_3" => "KIR", "currency_id" => "AUD", "ready" => false),
            array("iso" => "KM", "name" => "COMOROS", "nice_name" => "Comoros", "iso_3" => "COM", "currency_id" => "KMF", "ready" => false),
            array("iso" => "KN", "name" => "SAINT KITTS AND NEVIS", "nice_name" => "Saint Kitts and Nevis", "iso_3" => "KNA", "currency_id" => "XCD", "ready" => false),
            array("iso" => "KP", "name" => "NORTH KOREA", "nice_name" => "North Korea", "iso_3" => "PRK", "currency_id" => "KPW", "ready" => false),
            array("iso" => "KR", "name" => "SOUTH KOREA", "nice_name" => "South Korea", "iso_3" => "KOR", "currency_id" => "KRW", "ready" => false),
            array("iso" => "KW", "name" => "KUWAIT", "nice_name" => "Kuwait", "iso_3" => "KWT", "currency_id" => "KWD", "ready" => false),
            array("iso" => "KY", "name" => "CAYMAN ISLANDS", "nice_name" => "Cayman Islands", "iso_3" => "CYM", "currency_id" => "KYD", "ready" => false),
            array("iso" => "KZ", "name" => "KAZAKHSTAN", "nice_name" => "Kazakhstan", "iso_3" => "KAZ", "currency_id" => "KZT", "ready" => false),
            array("iso" => "LA", "name" => "LAOS", "nice_name" => "Laos", "iso_3" => "LAO", "currency_id" => "LAK", "ready" => false),
            array("iso" => "LB", "name" => "LEBANON", "nice_name" => "Lebanon", "iso_3" => "LBN", "currency_id" => "LBP", "ready" => false),
            array("iso" => "LC", "name" => "SAINT LUCIA", "nice_name" => "Saint Lucia", "iso_3" => "LCA", "currency_id" => "XCD", "ready" => false),
            array("iso" => "LI", "name" => "LIECHTENSTEIN", "nice_name" => "Liechtenstein", "iso_3" => "LIE", "currency_id" => "CHF", "ready" => false),
            array("iso" => "LK", "name" => "SRI LANKA", "nice_name" => "Sri Lanka", "iso_3" => "LKA", "currency_id" => "LKR", "ready" => false),
            array("iso" => "LR", "name" => "LIBERIA", "nice_name" => "Liberia", "iso_3" => "LBR", "currency_id" => "LRD", "ready" => false),
            array("iso" => "LS", "name" => "LESOTHO", "nice_name" => "Lesotho", "iso_3" => "LSO", "currency_id" => "LSL", "ready" => false),
            array("iso" => "LT", "name" => "LITHUANIA", "nice_name" => "Lithuania", "iso_3" => "LTU", "currency_id" => "LTL", "ready" => false),
            array("iso" => "LU", "name" => "LUXEMBOURG", "nice_name" => "Luxembourg", "iso_3" => "LUX", "currency_id" => "EUR", "ready" => false),
            array("iso" => "LV", "name" => "LATVIA", "nice_name" => "Latvia", "iso_3" => "LVA", "currency_id" => "EUR", "ready" => false),
            array("iso" => "LY", "name" => "LIBYA", "nice_name" => "Libya", "iso_3" => "LBY", "currency_id" => "LYD", "ready" => false),
            array("iso" => "MA", "name" => "MOROCCO", "nice_name" => "Morocco", "iso_3" => "MAR", "currency_id" => "MAD", "ready" => false),
            array("iso" => "MC", "name" => "MONACO", "nice_name" => "Monaco", "iso_3" => "MCO", "currency_id" => "EUR", "ready" => false),

        ));

        DB::table('countries')->insert(array(

            array("iso" => "MD", "name" => "MOLDOVA", "nice_name" => "Moldova", "iso_3" => "MDA", "currency_id" => "MDL", "ready" => false),
            array("iso" => "ME", "name" => "MONTENEGRO", "nice_name" => "Montenegro", "iso_3" => "MNE", "currency_id" => "EUR", "ready" => false),
            array("iso" => "MF", "name" => "SAINT MARTIN", "nice_name" => "Saint Martin", "iso_3" => "MAF", "currency_id" => "EUR", "ready" => false),
            array("iso" => "MG", "name" => "MADAGASCAR", "nice_name" => "Madagascar", "iso_3" => "MDG", "currency_id" => "MGA", "ready" => false),
            array("iso" => "MH", "name" => "MARSHALL ISLANDS", "nice_name" => "Marshall Islands", "iso_3" => "MHL", "currency_id" => "SAR", "ready" => false),
            array("iso" => "MK", "name" => "MACEDONIA (FYROM)", "nice_name" => "Macedonia (Fyrom)", "iso_3" => "MKD", "currency_id" => "MKD", "ready" => false),
            array("iso" => "ML", "name" => "MALI", "nice_name" => "Mali", "iso_3" => "MLI", "currency_id" => "XOF", "ready" => false),
            array("iso" => "MM", "name" => "REPUBLIC OF THE UNION OF MYANMAR", "nice_name" => "Myanmar (Burma)", "iso_3" => "MMR", "currency_id" => "BIF", "ready" => false),
            array("iso" => "MN", "name" => "MONGOLIA", "nice_name" => "Mongolia", "iso_3" => "MNG", "currency_id" => "MNT", "ready" => false),
            array("iso" => "MO", "name" => "MACAU", "nice_name" => "Macau", "iso_3" => "MAC", "currency_id" => "MOP", "ready" => false),
            array("iso" => "MP", "name" => "NORTHERN MARIANA ISLANDS", "nice_name" => "Northern Mariana Islands", "iso_3" => "MNP", "currency_id" => "SAR", "ready" => false),
            array("iso" => "MQ", "name" => "MARTINIQUE", "nice_name" => "Martinique", "iso_3" => "MTQ", "currency_id" => "EUR", "ready" => false),
            array("iso" => "MR", "name" => "MAURITANIA", "nice_name" => "Mauritania", "iso_3" => "MRT", "currency_id" => "MRO", "ready" => false),
            array("iso" => "MS", "name" => "MONTSERRAT", "nice_name" => "Montserrat", "iso_3" => "MSR", "currency_id" => "XCD", "ready" => false),
            array("iso" => "MT", "name" => "MALTA", "nice_name" => "Malta", "iso_3" => "MLT", "currency_id" => "EUR", "ready" => false),
            array("iso" => "MU", "name" => "MAURITIUS", "nice_name" => "Mauritius", "iso_3" => "MUS", "currency_id" => "MUR", "ready" => false),
            array("iso" => "MV", "name" => "MALDIVES", "nice_name" => "Maldives", "iso_3" => "MDV", "currency_id" => "MVR", "ready" => false),
            array("iso" => "MW", "name" => "MALAWI", "nice_name" => "Malawi", "iso_3" => "MWI", "currency_id" => "MWK", "ready" => false),
            array("iso" => "MX", "name" => "MEXICO", "nice_name" => "Mexico", "iso_3" => "MEX", "currency_id" => "MXN", "ready" => false),
            array("iso" => "MY", "name" => "MALAYSIA", "nice_name" => "Malaysia", "iso_3" => "MYS", "currency_id" => "MYR", "ready" => false),
            array("iso" => "MZ", "name" => "MOZAMBIQUE", "nice_name" => "Mozambique", "iso_3" => "MOZ", "currency_id" => "MZN", "ready" => false),
            array("iso" => "NA", "name" => "NAMIBIA", "nice_name" => "Namibia", "iso_3" => "NAM", "currency_id" => "NAD", "ready" => false),
            array("iso" => "NC", "name" => "NEW CALEDONIA", "nice_name" => "New Caledonia", "iso_3" => "NCL", "currency_id" => "XPF", "ready" => false),
            array("iso" => "NE", "name" => "NIGER", "nice_name" => "Niger", "iso_3" => "NER", "currency_id" => "XOF", "ready" => false),
            array("iso" => "NF", "name" => "NORFOLK ISLAND", "nice_name" => "Norfolk Island", "iso_3" => "NFK", "currency_id" => "AUD", "ready" => false),
            array("iso" => "NG", "name" => "NIGERIA", "nice_name" => "Nigeria", "iso_3" => "NGA", "currency_id" => "NGN", "ready" => false),
            array("iso" => "NI", "name" => "NICARAGUA", "nice_name" => "Nicaragua", "iso_3" => "NIC", "currency_id" => "NIO", "ready" => false),
            array("iso" => "NL", "name" => "THE NETHERLANDS", "nice_name" => "The Netherlands", "iso_3" => "NLD", "currency_id" => "EUR", "ready" => false),
            array("iso" => "NO", "name" => "NORWAY", "nice_name" => "Norway", "iso_3" => "NOR", "currency_id" => "NOK", "ready" => false),
            array("iso" => "NP", "name" => "NEPAL", "nice_name" => "Nepal", "iso_3" => "NPL", "currency_id" => "NPR", "ready" => false),
            array("iso" => "NR", "name" => "NAURU", "nice_name" => "Nauru", "iso_3" => "NRU", "currency_id" => "AUD", "ready" => false),
            array("iso" => "NU", "name" => "NIUE", "nice_name" => "Niue", "iso_3" => "NIU", "currency_id" => "NZD", "ready" => false),
            array("iso" => "NZ", "name" => "NEW ZEALAND", "nice_name" => "New Zealand", "iso_3" => "NZL", "currency_id" => "NZD", "ready" => false),
            array("iso" => "OM", "name" => "OMAN", "nice_name" => "Oman", "iso_3" => "OMN", "currency_id" => "OMR", "ready" => false),
            array("iso" => "PA", "name" => "PANAMA", "nice_name" => "Panama", "iso_3" => "PAN", "currency_id" => "SAR", "ready" => false),
            array("iso" => "PE", "name" => "PERU", "nice_name" => "Peru", "iso_3" => "PER", "currency_id" => "PEN", "ready" => false),
            array("iso" => "PF", "name" => "FRENCH POLYNESIA", "nice_name" => "French Polynesia", "iso_3" => "PYF", "currency_id" => "XPF", "ready" => false),
            array("iso" => "PG", "name" => "PAPUA NEW GUINEA", "nice_name" => "Papua New Guinea", "iso_3" => "PNG", "currency_id" => "PGK", "ready" => false),
            array("iso" => "PH", "name" => "PHILIPPINES", "nice_name" => "Philippines", "iso_3" => "PHL", "currency_id" => "PHP", "ready" => false),
            array("iso" => "PK", "name" => "PAKISTAN", "nice_name" => "Pakistan", "iso_3" => "PAK", "currency_id" => "PKR", "ready" => false),
            array("iso" => "PL", "name" => "POLAND", "nice_name" => "Poland", "iso_3" => "POL", "currency_id" => "PLN", "ready" => false),
            array("iso" => "PM", "name" => "SAINT PIERRE AND MIQUELON", "nice_name" => "Saint Pierre and Miquelon", "iso_3" => "SPM", "currency_id" => "EUR", "ready" => false),
            array("iso" => "PN", "name" => "PITCAIRN", "nice_name" => "Pitcairn", "iso_3" => "PCN","currency_id" => "NZD", "ready" => false),
            array("iso" => "PR", "name" => "PUERTO RICO", "nice_name" => "Puerto Rico", "iso_3" => "PRI", "currency_id" => "SAR", "ready" => false),
            array("iso" => "PS", "name" => "PALESTINIAN TERRITORY, OCCUPIED", "nice_name" => "Palestinian Territory, Occupied", "iso_3" => "PSE", "currency_id" => "ILS", "ready" => false),
            array("iso" => "PT", "name" => "PORTUGAL", "nice_name" => "Portugal", "iso_3" => "PRT", "currency_id" => "EUR", "ready" => false),
            array("iso" => "PW", "name" => "PALAU", "nice_name" => "Palau", "iso_3" => "PLW", "currency_id" => "SAR", "ready" => false),
            array("iso" => "PY", "name" => "PARAGUAY", "nice_name" => "Paraguay", "iso_3" => "PRY", "currency_id" => "PYG", "ready" => false),
            array("iso" => "QA", "name" => "QATAR", "nice_name" => "Qatar", "iso_3" => "QAT", "currency_id" => "QAR", "ready" => false),
            array("iso" => "RE", "name" => "REUNION", "nice_name" => "Reunion", "iso_3" => "REU", "currency_id" => "EUR", "ready" => false),
            array("iso" => "RO", "name" => "ROMANIA", "nice_name" => "Romania", "iso_3" => "ROM", "currency_id" => "RON", "ready" => false),

        ));

        DB::table('countries')->insert(array(

            array("iso" => "RS", "name" => "SERBIA", "nice_name" => "Serbia", "iso_3" => "SRB", "currency_id" => "RSD", "ready" => false),
            array("iso" => "RU", "name" => "RUSSIA", "nice_name" => "Russia", "iso_3" => "RUS", "currency_id" => "RUB", "ready" => false),
            array("iso" => "RW", "name" => "RWANDA", "nice_name" => "Rwanda", "iso_3" => "RWA", "currency_id" => "RWF", "ready" => false),
            array("iso" => "SA", "name" => "SAUDI ARABIA", "nice_name" => "Saudi Arabia", "iso_3" => "SAU", "currency_id" => "SAR", "ready" => false),
            array("iso" => "SB", "name" => "SOLOMON ISLANDS", "nice_name" => "Solomon Islands", "iso_3" => "SLB", "currency_id" => "SBD", "ready" => false),
            array("iso" => "SC", "name" => "SEYCHELLES", "nice_name" => "Seychelles", "iso_3" => "SYC", "currency_id" => "SCR", "ready" => false),
            array("iso" => "SD", "name" => "SUDAN", "nice_name" => "Sudan", "iso_3" => "SDN", "currency_id" => "SDG", "ready" => false),
            array("iso" => "SE", "name" => "SWEDEN", "nice_name" => "Sweden", "iso_3" => "SWE", "currency_id" => "SEK", "ready" => false),
            array("iso" => "SG", "name" => "SINGAPORE", "nice_name" => "Singapore", "iso_3" => "SGP", "currency_id" => "SGD", "ready" => false),
            array("iso" => "SH", "name" => "SAINT HELENA", "nice_name" => "Saint Helena", "iso_3" => "SHN", "currency_id" => "GBP", "ready" => false),
            array("iso" => "SI", "name" => "SLOVENIA", "nice_name" => "Slovenia", "iso_3" => "SVN", "currency_id" => "EUR", "ready" => false),
            array("iso" => "SJ", "name" => "SVALBARD AND JAN MAYEN", "nice_name" => "Svalbard and Jan Mayen", "iso_3" => "SJM", "currency_id" => "NOK", "ready" => false),
            array("iso" => "SK", "name" => "SLOVAKIA", "nice_name" => "Slovakia", "iso_3" => "SVK", "currency_id" => "EUR", "ready" => false),
            array("iso" => "SL", "name" => "SIERRA LEONE", "nice_name" => "Sierra Leone", "iso_3" => "SLE", "currency_id" => "SLL", "ready" => false),
            array("iso" => "SM", "name" => "SAN MARINO", "nice_name" => "San Marino", "iso_3" => "SMR", "currency_id" => "EUR", "ready" => false),
            array("iso" => "SN", "name" => "SENEGAL", "nice_name" => "Senegal", "iso_3" => "SEN", "currency_id" => "XOF", "ready" => false),
            array("iso" => "SO", "name" => "SOMALIA", "nice_name" => "Somalia", "iso_3" => "SOM", "currency_id" => "SOS", "ready" => false),
            array("iso" => "SR", "name" => "SURINAME", "nice_name" => "Suriname", "iso_3" => "SUR", "currency_id" => "SRD", "ready" => false),
            array("iso" => "SS", "name" => "SOUTH SUDAN", "nice_name" => "South Sudan", "iso_3" => "SSD", "currency_id" => "SDG", "ready" => false),
            array("iso" => "ST", "name" => "SAO TOME AND PRINCIPE", "nice_name" => "Sao Tome and Principe", "iso_3" => "STP", "currency_id" => "STD", "ready" => false),
            array("iso" => "SV", "name" => "EL SALVADOR", "nice_name" => "El Salvador", "iso_3" => "SLV", "currency_id" => "SAR", "ready" => false),
            array("iso" => "SX", "name" => "SINT MAARTEN", "nice_name" => "Sint Maarten", "iso_3" => "SXM", "currency_id" => "ANG", "ready" => false),
            array("iso" => "SY", "name" => "SYRIA", "nice_name" => "Syria", "iso_3" => "SYR", "currency_id" => "SYP", "ready" => false),
            array("iso" => "SZ", "name" => "SWAZILAND", "nice_name" => "Swaziland", "iso_3" => "SWZ", "currency_id" => "SZL", "ready" => false),
            array("iso" => "TC", "name" => "TURKS AND CAICOS ISLANDS", "nice_name" => "Turks and Caicos Islands", "iso_3" => "TCA", "currency_id" => "SAR", "ready" => false),
            array("iso" => "TD", "name" => "CHAD", "nice_name" => "Chad", "iso_3" => "TCD", "currency_id" => "XAF", "ready" => false),
            array("iso" => "TF", "name" => "FRENCH SOUTHERN TERRITORIES", "nice_name" => "French Southern Territores", "iso_3" => "ATF","currency_id" => "EUR", "ready" => false),
            array("iso" => "TG", "name" => "TOGO", "nice_name" => "Togo", "iso_3" => "TGO", "currency_id" => "XOF", "ready" => false),
            array("iso" => "TH", "name" => "THAILAND", "nice_name" => "Thailand", "iso_3" => "THA", "currency_id" => "THB", "ready" => false),
            array("iso" => "TJ", "name" => "TAJIKISTAN", "nice_name" => "Tajikistan", "iso_3" => "TJK", "currency_id" => "TJS", "ready" => false),
            array("iso" => "TK", "name" => "TOKELAU", "nice_name" => "Tokelau", "iso_3" => "TKL", "currency_id" => "NZD", "ready" => false),
            array("iso" => "TL", "name" => "TIMOR-LESTE", "nice_name" => "Timor-Leste", "iso_3" => "TLS", "currency_id" => "SAR", "ready" => false),
            array("iso" => "TM", "name" => "TURKMENISTAN", "nice_name" => "Turkmenistan", "iso_3" => "TKM", "currency_id" => "TMT", "ready" => false),
            array("iso" => "TN", "name" => "TUNISIA", "nice_name" => "Tunisia", "iso_3" => "TUN", "currency_id" => "TND", "ready" => false),
            array("iso" => "TO", "name" => "TONGA", "nice_name" => "Tonga", "iso_3" => "TON", "currency_id" => "TOP", "ready" => false),
            array("iso" => "TR", "name" => "TURKEY", "nice_name" => "Turkey", "iso_3" => "TUR", "currency_id" => "TRY", "ready" => false),
            array("iso" => "TT", "name" => "TRINIDAD AND TOBAGO", "nice_name" => "Trinidad and Tobago", "iso_3" => "TTO", "currency_id" => "TTD", "ready" => false),
            array("iso" => "TV", "name" => "TUVALU", "nice_name" => "Tuvalu", "iso_3" => "TUV", "currency_id" => "TVD", "ready" => false),
            array("iso" => "TW", "name" => "TAIWAN", "nice_name" => "Taiwan", "iso_3" => "TWN", "currency_id" => "TWD", "ready" => false),
            array("iso" => "TZ", "name" => "TANZANIA", "nice_name" => "Tanzania", "iso_3" => "TZA", "currency_id" => "TZS", "ready" => false),
            array("iso" => "UA", "name" => "UKRAINE", "nice_name" => "Ukraine", "iso_3" => "UKR", "currency_id" => "UAH", "ready" => false),
            array("iso" => "UG", "name" => "UGANDA", "nice_name" => "Uganda", "iso_3" => "UGA", "currency_id" => "UGX", "ready" => false),
            array("iso" => "UM", "name" => "UNITED STATES MINOR OUTLYING ISLANDS", "nice_name" => "United States Minor Outlying Islands", "iso_3" => "UMI", "currency_id" => "SAR", "ready" => false),
            array("iso" => "US", "name" => "UNITED STATES", "nice_name" => "United States", "iso_3" => "USA", "currency_id" => "SAR", "ready" => false),
            array("iso" => "UY", "name" => "URUGUAY", "nice_name" => "Uruguay", "iso_3" => "URY", "currency_id" => "UYU", "ready" => false),
            array("iso" => "UZ", "name" => "UZBEKISTAN", "nice_name" => "Uzbekistan", "iso_3" => "UZB", "currency_id" => "UZS", "ready" => false),
            array("iso" => "VA", "name" => "VATICAN CITY", "nice_name" => "Vatican City", "iso_3" => "VAT", "currency_id" => "EUR", "ready" => false),
            array("iso" => "VC", "name" => "SAINT VINCENT AND THE GRENADINES", "nice_name" => "Saint Vincent and the Grenadines", "iso_3" => "VCT", "currency_id" => "XCD", "ready" => false),
            array("iso" => "VE", "name" => "VENEZUELA", "nice_name" => "Venezuela", "iso_3" => "VEN", "currency_id" => "VEF", "ready" => false),
            array("iso" => "VG", "name" => "BRITISH VIRGIN ISLANDS", "nice_name" => "Virgin Islands, British", "iso_3" => "VGB", "currency_id" => "SAR", "ready" => false),
            array("iso" => "VI", "name" => "U.S. VIRGIN ISLANDS", "nice_name" => "Virgin Islands, U.S.", "iso_3" => "VIR", "currency_id" => "SAR", "ready" => false),
            array("iso" => "VN", "name" => "VIETNAM", "nice_name" => "Vietnam", "iso_3" => "VNM", "currency_id" => "VND", "ready" => false),
            array("iso" => "VU", "name" => "VANUATU", "nice_name" => "Vanuatu", "iso_3" => "VUT", "currency_id" => "VND", "ready" => false),
            array("iso" => "WF", "name" => "WALLIS AND FUTUNA", "nice_name" => "Wallis and Futuna", "iso_3" => "WLF", "currency_id" => "XPF", "ready" => false),
            array("iso" => "WS", "name" => "SAMOA", "nice_name" => "Samoa", "iso_3" => "WSM", "currency_id" => "WST", "ready" => false),
            array("iso" => "YE", "name" => "YEMEN", "nice_name" => "Yemen", "iso_3" => "YEM", "currency_id" => "YER", "ready" => false),
            array("iso" => "YT", "name" => "MAYOTTE", "nice_name" => "Mayotte", "iso_3" => "MYT", "currency_id" => "EUR", "ready" => false),
            array("iso" => "ZA", "name" => "SOUTH AFRICA", "nice_name" => "South Africa", "iso_3" => "ZAF", "currency_id" => "ZAR", "ready" => false),
            array("iso" => "ZM", "name" => "ZAMBIA", "nice_name" => "Zambia", "iso_3" => "ZMB", "currency_id" => "ZMW", "ready" => false),
            array("iso" => "ZW", "name" => "ZIMBABWE", "nice_name" => "Zimbabwe", "iso_3" => "ZWE", "currency_id" => "ZWD", "ready" => false),

        ));

    }
}